resolver: lts-12.1

packages:
- '.'

extra-deps:
- transformers-either-0.1.1

# Override default flag values for local packages and extra-deps
flags: {}

# Extra package databases containing global packages
extra-package-dbs: []

